[package]
name = "learning_rust"
version = "0.1.0"
authors = ["Haiaty varotto <you@example.com>"]
edition = "2018"

[[bin]]
name = "test"
path = "src/match.rs"
#path = "src/scripts/practice_references.rs"

[dependencies]